In [ ]:
import pandas as pd

# pd.set_option('display.max_rows', None)
# pd.set_option('display.max_columns', None)
# pd.reset_option('display.max_rows')
# pd.reset_option('display.max_columns')

df1 = pd.read_excel(r"C:\Users\hyste\OneDrive\Έγγραφα\Python\My Projects\Github Repo\Coffee-Beans-Sales-Analysis\data\Raw Data.xlsx",
                    sheet_name='orders',
                    header=0,)
df2 = pd.read_excel(r"C:\Users\hyste\OneDrive\Έγγραφα\Python\My Projects\Github Repo\Coffee-Beans-Sales-Analysis\data\Raw Data.xlsx",
                    sheet_name='customers',
                    header=0,)
df3 = pd.read_excel(r"C:\Users\hyste\OneDrive\Έγγραφα\Python\My Projects\Github Repo\Coffee-Beans-Sales-Analysis\data\Raw Data.xlsx",
                    sheet_name='products',
                    header=0,)

df1=df1[['Order ID','Order Date','Customer ID','Product ID','Quantity']]

display(df1,df2,df3)

combined = pd.merge(df1, df2, on='Customer ID', how='left')
combined = pd.merge(combined, df3, on='Product ID', how='left')
combined = combined.sort_values(by='Order Date')

combined['Day'] = combined['Order Date'].dt.day
combined['Weekday'] = combined['Order Date'].dt.day_name()
combined['Month'] = combined['Order Date'].dt.month
combined['Year'] = combined['Order Date'].dt.year

display(combined)
# combined.dtypes

          Order ID Order Date     Customer ID Product ID  Quantity
0    QEV-37451-860 2019-09-05  17670-51384-MA      R-M-1         2
1    QEV-37451-860 2019-09-05  17670-51384-MA    E-M-0.5         5
2    FAA-43335-268 2021-06-17  21125-22134-PX      A-L-1         1
3    KAC-83089-793 2021-07-15  23806-46781-OU      E-M-1         2
4    KAC-83089-793 2021-07-15  23806-46781-OU    R-L-2.5         2
..             ...        ...             ...        ...       ...
995  RLM-96511-467 2020-01-06  43014-53743-XK    R-L-2.5         1
996  AEZ-13242-456 2022-05-04  62494-09113-RP    R-M-0.5         5
997  UME-75640-698 2019-10-11  62494-09113-RP    A-M-0.5         4
998  GJC-66474-557 2021-08-03  64965-78386-MY      A-D-1         1
999  IRV-20769-219 2020-10-15  77131-58092-GE    E-M-0.2         3

[1000 rows x 5 columns]

,Customer ID,Customer Name,Email,Phone Number,Address Line 1,City,Country,Postcode,Loyalty Card
0,17670-51384-MA,Aloisia Allner,aallner0@lulu.com,+1 (862) 817-0124,57999 Pepper Wood Alley,Paterson,United States,7505,Yes
1,73342-18763-UW,Piotr Bote,pbote1@yelp.com,+353 (913) 396-4653,2112 Ridgeway Hill,Crumlin,Ireland,D6W,No
2,21125-22134-PX,Jami Redholes,jredholes2@tmall.com,+1 (210) 986-6806,5214 Bartillon Park,San Antonio,United States,78205,Yes
3,71253-00052-RN,Dene Azema,dazema3@facebook.com,+1 (217) 418-0714,27 Maywood Place,Springfield,United States,62711,Yes
4,23806-46781-OU,Christoffer O' Shea,NaN,+353 (698) 362-9201,38980 Manitowish Junction,Cill Airne,Ireland,N41,No
...,...,...,...,...,...,...,...,...,...
995,43014-53743-XK,Jennica Tewelson,jtewelsonrn@samsung.com,+1 (469) 573-8379,4040 Hoard Junction,Dallas,United States,75210,No
996,62494-09113-RP,Marguerite Graves,NaN,+1 (479) 204-9111,91413 Scott Way,Fort Smith,United States,72905,No
997,10940-42739-ET,Etan Featenby,NaN,+1 (719) 416-9560,885 Toban Plaza,Colorado Springs,United States,80920,Yes
998,64965-78386-MY,Nicolina Jenny,njennyrq@bigcartel.com,+1 (562) 679-4750,6099 American Ash Court,Whittier,United States,90610,No
999,77131-58092-GE,Vidovic Antonelli,NaN,+44 (810) 927-9266,3242 Corscot Pass,London,United Kingdom,EC1V,Yes

,Product ID,Coffee Type,Roast Type,Size,Unit Price,Price per 100g,Profit
0,A-L-0.2,Ara,L,0.2,3.885,1.9425,0.34965
1,A-L-0.5,Ara,L,0.5,7.770,1.5540,0.69930
2,A-L-1,Ara,L,1.0,12.950,1.2950,1.16550
3,A-L-2.5,Ara,L,2.5,29.785,1.1914,2.68065
4,A-M-0.2,Ara,M,0.2,3.375,1.6875,0.30375
5,A-M-0.5,Ara,M,0.5,6.750,1.3500,0.60750
6,A-M-1,Ara,M,1.0,11.250,1.1250,1.01250
7,A-M-2.5,Ara,M,2.5,25.875,1.0350,2.32875
8,A-D-0.2,Ara,D,0.2,2.985,1.4925,0.26865
9,A-D-0.5,Ara,D,0.5,5.970,1.1940,0.53730
10,A-D-1,Ara,D,1.0,9.950,0.9950,0.89550
11,A-D-2.5,Ara,D,2.5,22.885,0.9154,2.05965
12,R-L-0.2,Rob,L,0.2,3.585,1.7925,0.21510
13,R-L-0.5,Rob,L,0.5,7.170,1.4340,0.43020
14,R-L-1,Rob,L,1.0,11.950,1.1950,0.71700
15,R-L-2.5,Rob,L,2.5,27.485,1.0994,1.64910
16,R-M-0.2,Rob,M,0.2,2.985,1.4925,0.17910
17,R-M-0.5,Rob,M,0.5,5.970,1.1940,0.35820
18,R-M-1,Rob,M,1.0,9.950,0.9950,0.59700
19,R-M-2.5,Rob,M,2.5,22.885,0.9154,1.37310
20,R-D-0.2,Rob,D,0.2,2.685,1.3425,0.16110
21,R-D-0.5,Rob,D,0.5,5.370,1.0740,0.32220
22,R-D-1,Rob,D,1.0,8.950,0.8950,0.53700
23,R-D-2.5,Rob,D,2.5,20.585,0.8234,1.23510
24,L-L-0.2,Lib,L,0.2,4.755,2.3775,0.61815
25,L-L-0.5,Lib,L,0.5,9.510,1.9020,1.23630
26,L-L-1,Lib,L,1.0,15.850,1.5850,2.06050
27,L-L-2.5,Lib,L,2.5,36.455,1.4582,4.73915
28,L-M-0.2,Lib,M,0.2,4.365,2.1825,0.56745
29,L-M-0.5,Lib,M,0.5,8.730,1.7460,1.13490
30,L-M-1,Lib,M,1.0,14.550,1.4550,1.89150
31,L-M-2.5,Lib,M,2.5,33.465,1.3386,4.35045
32,L-D-0.2,Lib,D,0.2,3.885,1.9425,0.50505
33,L-D-0.5,Lib,D,0.5,7.770,1.5540,1.01010
34,L-D-1,Lib,D,1.0,12.950,1.2950,1.68350
35,L-D-2.5,Lib,D,2.5,29.785,1.1914,3.87205
36,E-L-0.2,Exc,L,0.2,4.455,2.2275,0.49005
37,E-L-0.5,Exc,L,0.5,8.910,1.7820,0.98010
38,E-L-1,Exc,L,1.0,14.850,1.4850,1.63350
39,E-L-2.5,Exc,L,2.5,34.155,1.3662,3.75705
40,E-M-0.2,Exc,M,0.2,4.125,2.0625,0.45375
41,E-M-0.5,Exc,M,0.5,8.250,1.6500,0.90750
42,E-M-1,Exc,M,1.0,13.750,1.3750,1.51250
43,E-M-2.5,Exc,M,2.5,31.625,1.2650,3.47875
44,E-D-0.2,Exc,D,0.2,3.645,1.8225,0.40095
45,E-D-0.5,Exc,D,0.5,7.290,1.4580,0.80190
46,E-D-1,Exc,D,1.0,12.150,1.2150,1.33650
47,E-D-2.5,Exc,D,2.5,27.945,1.1178,3.07395

,Order ID,Order Date,Customer ID,Product ID,Quantity,Customer Name,Email,Phone Number,Address Line 1,City,...,Coffee Type,Roast Type,Size,Unit Price,Price per 100g,Profit,Day,Weekday,Month,Year
502,CTE-31437-326,2019-01-02,22721-63196-UJ,E-M-0.2,4,Gladi Ducker,gduckerdx@patch.com,+44 (749) 987-9016,5069 Boyd Parkway,Belfast,...,Exc,M,0.2,4.125,2.0625,0.45375,2,Wednesday,1,2019
504,CTE-31437-326,2019-01-02,22721-63196-UJ,L-L-0.2,3,Gladi Ducker,gduckerdx@patch.com,+44 (749) 987-9016,5069 Boyd Parkway,Belfast,...,Lib,L,0.2,4.755,2.3775,0.61815,2,Wednesday,1,2019
503,CTE-31437-326,2019-01-02,22721-63196-UJ,L-D-1,4,Gladi Ducker,gduckerdx@patch.com,+44 (749) 987-9016,5069 Boyd Parkway,Belfast,...,Lib,D,1.0,12.950,1.2950,1.68350,2,Wednesday,1,2019
501,CTE-31437-326,2019-01-02,22721-63196-UJ,R-M-0.2,4,Gladi Ducker,gduckerdx@patch.com,+44 (749) 987-9016,5069 Boyd Parkway,Belfast,...,Rob,M,0.2,2.985,1.4925,0.17910,2,Wednesday,1,2019
8,EZT-46571-659,2019-01-02,03396-68805-ZC,R-M-0.5,3,Guthrey Petracci,gpetracci8@livejournal.com,+1 (310) 868-1842,949 Paget Parkway,Los Angeles,...,Rob,M,0.5,5.970,1.1940,0.35820,2,Wednesday,1,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,XUR-14132-391,2022-08-08,96836-09258-RI,R-D-0.5,4,Lisa Goodger,lgoodger95@guardian.co.uk,NaN,86634 Nova Plaza,Sacramento,...,Rob,D,0.5,5.370,1.0740,0.32220,8,Monday,8,2022
982,SNZ-44595-152,2022-08-12,06136-65250-PG,R-L-1,2,Kim Kemery,kkemeryra@t.co,+1 (817) 407-3513,95 Delladonna Parkway,Denton,...,Rob,L,1.0,11.950,1.1950,0.71700,12,Friday,8,2022
49,PQA-54820-810,2022-08-17,91460-04823-BX,A-L-1,3,Isis Pikett,ipikett1d@xinhuanet.com,+1 (202) 871-9039,5892 Hauk Drive,Washington,...,Ara,L,1.0,12.950,1.2950,1.16550,17,Wednesday,8,2022
50,XKB-41924-202,2022-08-19,45089-52817-WN,L-D-0.5,2,Inger Bouldon,ibouldon1e@gizmodo.com,+1 (754) 391-4736,925 Barby Circle,Fort Lauderdale,...,Lib,D,0.5,7.770,1.5540,1.01010,19,Friday,8,2022
867,HHO-79903-185,2022-08-19,53893-01719-CL,A-L-2.5,1,Bee Fattorini,bfattorinio3@quantcast.com,NaN,433 Caliangt Park,Monaghan,...,Ara,L,2.5,29.785,1.1914,2.68065,19,Friday,8,2022

Order ID                  object
Order Date        datetime64[ns]
Customer ID               object
Product ID                object
Quantity                   int64
Customer Name             object
Email                     object
Phone Number              object
Address Line 1            object
City                      object
Country                   object
Postcode                  object
Loyalty Card              object
Coffee Type               object
Roast Type                object
Size                     float64
Unit Price               float64
Price per 100g           float64
Profit                   float64
Day                        int32
Weekday                   object
Month                      int32
Year                       int32
dtype: object

In [2]:
combined['Coffee Type'] = combined['Coffee Type'].str.replace('Ara', 'Arabica')
combined['Coffee Type'] = combined['Coffee Type'].str.replace('Rob', 'Robusta')
combined['Coffee Type'] = combined['Coffee Type'].str.replace('Exc', 'Excelsa')
combined['Coffee Type'] = combined['Coffee Type'].str.replace('Lib', 'Liberica')

combined['Roast Type'] = combined['Roast Type'].str.replace('L', 'Light Roast')
combined['Roast Type'] = combined['Roast Type'].str.replace('M', 'Medium Roast')
combined['Roast Type'] = combined['Roast Type'].str.replace('D', 'Dark Roast')

# combined.replace({  'Roast Type': {'L': 'Light', 'M': 'Medium', 'D': 'Dark'},
#                     'Coffee Type': {'Ara': 'Arabica', 'Rob': 'Robusta', 'Exc': 'Excelsa', 'Lib': 'Liberica'}}, inplace=True)

In [3]:
combined = combined.drop(columns = 'Price per 100g')

combined['Revenue'] = combined['Unit Price'] * combined['Quantity']

cols = list(combined.columns)
q = cols.pop(cols.index('Quantity'))
cols.insert(cols.index('Roast Type') + 1, q)
r = cols.pop(cols.index('Revenue'))
cols.insert(cols.index('Unit Price') + 1, r)

combined = combined[cols]

combined

,Order ID,Order Date,Customer ID,Product ID,Customer Name,Email,Phone Number,Address Line 1,City,Country,...,Roast Type,Quantity,Size,Unit Price,Revenue,Profit,Day,Weekday,Month,Year
502,CTE-31437-326,2019-01-02,22721-63196-UJ,E-M-0.2,Gladi Ducker,gduckerdx@patch.com,+44 (749) 987-9016,5069 Boyd Parkway,Belfast,United Kingdom,...,Medium Roast,4,0.2,4.125,16.500,0.45375,2,Wednesday,1,2019
504,CTE-31437-326,2019-01-02,22721-63196-UJ,L-L-0.2,Gladi Ducker,gduckerdx@patch.com,+44 (749) 987-9016,5069 Boyd Parkway,Belfast,United Kingdom,...,Light Roast,3,0.2,4.755,14.265,0.61815,2,Wednesday,1,2019
503,CTE-31437-326,2019-01-02,22721-63196-UJ,L-D-1,Gladi Ducker,gduckerdx@patch.com,+44 (749) 987-9016,5069 Boyd Parkway,Belfast,United Kingdom,...,Dark Roast,4,1.0,12.950,51.800,1.68350,2,Wednesday,1,2019
501,CTE-31437-326,2019-01-02,22721-63196-UJ,R-M-0.2,Gladi Ducker,gduckerdx@patch.com,+44 (749) 987-9016,5069 Boyd Parkway,Belfast,United Kingdom,...,Medium Roast,4,0.2,2.985,11.940,0.17910,2,Wednesday,1,2019
8,EZT-46571-659,2019-01-02,03396-68805-ZC,R-M-0.5,Guthrey Petracci,gpetracci8@livejournal.com,+1 (310) 868-1842,949 Paget Parkway,Los Angeles,United States,...,Medium Roast,3,0.5,5.970,17.910,0.35820,2,Wednesday,1,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,XUR-14132-391,2022-08-08,96836-09258-RI,R-D-0.5,Lisa Goodger,lgoodger95@guardian.co.uk,NaN,86634 Nova Plaza,Sacramento,United States,...,Dark Roast,4,0.5,5.370,21.480,0.32220,8,Monday,8,2022
982,SNZ-44595-152,2022-08-12,06136-65250-PG,R-L-1,Kim Kemery,kkemeryra@t.co,+1 (817) 407-3513,95 Delladonna Parkway,Denton,United States,...,Light Roast,2,1.0,11.950,23.900,0.71700,12,Friday,8,2022
49,PQA-54820-810,2022-08-17,91460-04823-BX,A-L-1,Isis Pikett,ipikett1d@xinhuanet.com,+1 (202) 871-9039,5892 Hauk Drive,Washington,United States,...,Light Roast,3,1.0,12.950,38.850,1.16550,17,Wednesday,8,2022
50,XKB-41924-202,2022-08-19,45089-52817-WN,L-D-0.5,Inger Bouldon,ibouldon1e@gizmodo.com,+1 (754) 391-4736,925 Barby Circle,Fort Lauderdale,United States,...,Dark Roast,2,0.5,7.770,15.540,1.01010,19,Friday,8,2022
867,HHO-79903-185,2022-08-19,53893-01719-CL,A-L-2.5,Bee Fattorini,bfattorinio3@quantcast.com,NaN,433 Caliangt Park,Monaghan,Ireland,...,Light Roast,1,2.5,29.785,29.785,2.68065,19,Friday,8,2022

In [4]:
combined.to_csv(r"C:\Users\hyste\OneDrive\Έγγραφα\Python\My Projects\Github Repo\Coffee-Beans-Sales-Analysis\cleaning\orders_clean_by_me.csv", index=False)

## FROM THIS POINT ON, I WILL PROGRESS WITH FILIPPOS'S FILE

In [ ]:
cleaned_data = pd.read_csv(r"C:\Users\hyste\OneDrive\Έγγραφα\Python\My Projects\Github Repo\Coffee-Beans-Sales-Analysis\cleaning\orders_clean_by_filippos.csv",
                    # sheet_name='orders_clean_by_filippos',
                    header=0,)

cleaned_data

# (exactly same file as mine, only difference is that i have re-arranged the 'Quantity' and the 'Revenue' columns)

,Order ID,Order Date,Customer ID,Product ID,Quantity,Customer Name,Email,Phone Number,Address Line 1,City,...,Loyalty Card,Coffee Type,Roast Type,Size,Unit Price,Profit,Weekday,Month,Year,Revenue
0,QEV-37451-860,2019-09-05,17670-51384-MA,R-M-1,2,Aloisia Allner,aallner0@lulu.com,+1 (862) 817-0124,57999 Pepper Wood Alley,Paterson,...,Yes,Robusta,Medium,1.0,9.950,0.59700,Thursday,9,2019,19.900
1,QEV-37451-860,2019-09-05,17670-51384-MA,E-M-0.5,5,Aloisia Allner,aallner0@lulu.com,+1 (862) 817-0124,57999 Pepper Wood Alley,Paterson,...,Yes,Excelsa,Medium,0.5,8.250,0.90750,Thursday,9,2019,41.250
2,FAA-43335-268,2021-06-17,21125-22134-PX,A-L-1,1,Jami Redholes,jredholes2@tmall.com,+1 (210) 986-6806,5214 Bartillon Park,San Antonio,...,Yes,Arabica,Light,1.0,12.950,1.16550,Thursday,6,2021,12.950
3,KAC-83089-793,2021-07-15,23806-46781-OU,E-M-1,2,Christoffer O' Shea,NaN,+353 (698) 362-9201,38980 Manitowish Junction,Cill Airne,...,No,Excelsa,Medium,1.0,13.750,1.51250,Thursday,7,2021,27.500
4,KAC-83089-793,2021-07-15,23806-46781-OU,R-L-2.5,2,Christoffer O' Shea,NaN,+353 (698) 362-9201,38980 Manitowish Junction,Cill Airne,...,No,Robusta,Light,2.5,27.485,1.64910,Thursday,7,2021,54.970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,RLM-96511-467,2020-01-06,43014-53743-XK,R-L-2.5,1,Jennica Tewelson,jtewelsonrn@samsung.com,+1 (469) 573-8379,4040 Hoard Junction,Dallas,...,No,Robusta,Light,2.5,27.485,1.64910,Monday,1,2020,27.485
996,AEZ-13242-456,2022-05-04,62494-09113-RP,R-M-0.5,5,Marguerite Graves,NaN,+1 (479) 204-9111,91413 Scott Way,Fort Smith,...,No,Robusta,Medium,0.5,5.970,0.35820,Wednesday,5,2022,29.850
997,UME-75640-698,2019-10-11,62494-09113-RP,A-M-0.5,4,Marguerite Graves,NaN,+1 (479) 204-9111,91413 Scott Way,Fort Smith,...,No,Arabica,Medium,0.5,6.750,0.60750,Friday,10,2019,27.000
998,GJC-66474-557,2021-08-03,64965-78386-MY,A-D-1,1,Nicolina Jenny,njennyrq@bigcartel.com,+1 (562) 679-4750,6099 American Ash Court,Whittier,...,No,Arabica,Dark,1.0,9.950,0.89550,Tuesday,8,2021,9.950
999,IRV-20769-219,2020-10-15,77131-58092-GE,E-M-0.2,3,Vidovic Antonelli,NaN,+44 (810) 927-9266,3242 Corscot Pass,London,...,Yes,Excelsa,Medium,0.2,4.125,0.45375,Thursday,10,2020,12.375